eureka:
  instance:
    hostname: localhost
server:
  port: 8090
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      default-filters:
#      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#              allowedOrigins: "http://localhost:4200/"
#              allowedMethods: 
#              - POST
#              - GET
#              - OPTIONS
#              allowedHeaders: "*"
#              allowCredentials: true

      routes:
      - id: auth
        uri: http://localhost:8081/
        predicates:
        - Path=/auth/**
        
      - id: loan
        uri: http://localhost:8082/
        predicates:
        - Path=/loan/**

      - id: process
        uri: http://localhost:8083/
        predicates:
        - Path=/process/**
        
      - id: member
        uri: http://localhost:8084/
        predicates:
        - Path=/member/**  
        
      - id: registration
        uri: http://localhost:5001/
        predicates:
        - Path=/registration/** 
     

        
        
